import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import ThemeLayout from "@/components/layouts/ThemeLayout";
import ReactQueryProvider from "@/components/providers/ReactQuery";
import "./globals.scss";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeLayout options={{ key: "mui" }}>
          <ReactQueryProvider>
            <Header />
            {children}
            <Footer />
          </ReactQueryProvider>
        </ThemeLayout>
      </body>
    </html>
  );
}
